// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5wo9iyWrmfyyWMlPkj9IP30RYYnt30X0',
    appId: '1:1038213869981:web:345a3c137d869e7022bf74',
    messagingSenderId: '1038213869981',
    projectId: 'idea-ecommerce-app',
    authDomain: 'idea-ecommerce-app.firebaseapp.com',
    storageBucket: 'idea-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpC-8oBrh0rrZju6msEwhdSH2z0YKdgG4',
    appId: '1:1038213869981:android:2c80480da4a59dfe22bf74',
    messagingSenderId: '1038213869981',
    projectId: 'idea-ecommerce-app',
    storageBucket: 'idea-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD5PMT1pclLgZjY9eYTfeEPJbZ6OD5PB0',
    appId: '1:1038213869981:ios:241d5c1cdc9cec1a22bf74',
    messagingSenderId: '1038213869981',
    projectId: 'idea-ecommerce-app',
    storageBucket: 'idea-ecommerce-app.appspot.com',
    androidClientId: '1038213869981-g262qta9darbtd7l7m3qig4gssju2p3f.apps.googleusercontent.com',
    iosClientId: '1038213869981-4ppg35pfd494qetemkgijt1fepr1rusu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ideaEcommerceApp',
  );
}
